Goslmailer install
centerforaisafety/cerberus-cluster pull request #109
Opened 2023-06-13 21:23 UTC by rumiahkessel

Adds Goslmailer ansible playbook. This installs Mutt and all requisite config files and directories from our fork of goslmailer.

2023-06-13 21:36 UTC, steven-basart requested changes
Some comments. 

Additionally where and how is the token set. 
Update the README docs are important.

2023-06-13 21:36 UTC, steven-basart commented on playbooks/goslmailer_install.yml
This file should be one of the roles in CAIS bastion is my guess or `cais_all` if it needs to be in all of the nodes.

2023-06-13 21:36 UTC, steven-basart commented on playbooks/goslmailer_install.yml
Can also be under slurm role too tbh.

2023-06-13 21:36 UTC, steven-basart commented on playbooks/goslmailer_install.yml
> +        path: /var/spool/slack
Doesn't this one already exist?

2023-06-13 21:36 UTC, steven-basart commented on playbooks/goslmailer_install.yml
> +        path: /var/log/goslmailer.log
We don't want to save the logs to /data the local storage will fill up quickly is my guess.

2023-06-13 21:36 UTC, steven-basart commented on playbooks/goslmailer_install.yml
> +    - name: Reload systemd daemon
Is this right? Seems like you're reloading systemd without any arguments? Shouldn't you reload the new daemon?

2023-06-13 21:36 UTC, steven-basart commented on playbooks/goslmailer_install.yml
> +    # - name: Disable gobler service
Comments left in

2023-06-13 21:36 UTC, steven-basart commented on playbooks/goslmailer_install.yml
> +    - name: Install mutt
Double check if this is already installed. Don't remember

2023-06-13 21:36 UTC, steven-basart commented on playbooks/goslmailer_install.yml
> +        - { path: '/var/spool/mail', mode: '0755'}
Does this need to be in spool? Maybe make it a symlink to somewhere in /data

2023-06-13 21:37 UTC, steven-basart commented
Please reference the git issue somewhere in the pr so I can go back to look at it as well.

2023-06-13 21:38 UTC, rumiahkessel commented
Sorry I shouldn't have pinged you yet I was still writing the request

2023-06-13 21:43 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
> +        path: /var/spool/slack
if you are referring to the spool/slack directory it does not.

2023-06-13 21:44 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
> +        path: /var/log/goslmailer.log
This is where the slurm logs are currently stored, so I figured I should put them in the same place. Do you have a suggestion of where I should put them?

2023-06-13 21:45 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
> +    - name: Reload systemd daemon
seems github cut it off but the actual line says: 
```
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
```

2023-06-13 21:46 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
> +    - name: Install mutt
It is not.

2023-06-13 21:47 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
> +    # - name: Disable gobler service
This was intentional. These are the lines you would edit to enable spooling of the slack notifications. I will describe all of this in the eng-docs, but I wanted to make it as easy as possible to enable spooling in the future if we see the need for it.

2023-06-13 21:48 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
> +        - { path: '/var/spool/mail', mode: '0755'}
Neither of these save data long term. It is just for spooling messages instantaneously and these were the default locations. (These already both exist on prod in spool)

2023-06-13 21:54 UTC, andriy-safe-ai commented on playbooks/goslmailer_install.yml
> +        path: /var/log/goslmailer.log
We do or we don't?

2023-06-13 22:34 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
> +        path: /var/log/goslmailer.log
Looking into it the logs generate a lot of data and there is no less verbose option. You can, however, direct the outputs to stderr and only log when we are encountering problems. I have done that and committed. If notifications do stop working we can load the playbooks from the previous commit and it will install logging and everything for us to diagnose the issue.

2023-06-13 23:47 UTC, steven-basart commented on playbooks/goslmailer_install.yml
> +        path: /var/log/goslmailer.log
Sorry was typing too quickly. I meant we want to save the logs to /data.

2023-06-13 23:48 UTC, steven-basart commented on playbooks/goslmailer_install.yml
> +        path: /var/log/goslmailer.log
Also this is not where the logs are stored in prod. Please have a look. You'll notice in prod that /var/spool/ logs are symlinks.

2023-06-13 23:49 UTC, steven-basart commented on playbooks/goslmailer_install.yml
> +        path: /var/spool/slack
You're right I read it too quickly. I thought it was "spack" which we also have and have yet to delete.

2023-06-13 23:53 UTC, steven-basart commented on playbooks/goslmailer_install.yml
> +    # - name: Disable gobler service
It's bad practice or form to leave them in. Documentation should be the place for this or a GitHub issue or both. 

Code should be the source of truth for code. Comments left in for unused code are just confusing for whomever next comes in and wants to debug.

2023-06-14 00:23 UTC, steven-basart commented on playbooks/goslmailer_install.yml
It's more an organizational thing. Things should be organized with other files similar to where they belong. Let me know if you're unfamiliar with the other roles files. Not sure we need a new role for this? 
More i think about it more i think it should be included with SLURM role.

2023-06-14 15:21 UTC, steven-basart commented
One last thing before I forget. Squash or fixup your commits before merging.

2023-06-14 20:14 UTC, andriy-safe-ai commented on playbooks/goslmailer_install.yml
Are you suggesting to include the `goslmailer` role under the `Slurm` roles tasks?

2023-06-14 20:15 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
> +    # - name: Disable gobler service
Fixed and addressed in eng-docs. Full instructions for how to enable spooling are there now and no comments.

2023-06-14 20:26 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
> +        path: /var/log/goslmailer.log
Given the sheer number of logs the mailer produces I don't think it's a good idea to have it running constantly. Unfortunately the program does not have a less verbose option (we can edit the source code to remove some of the prints but I don't think that is worth the time it would take and to make sure we don't remove any useful ones). When we have an issue we can easily enable the logs.

2023-06-14 21:15 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
One thing is that this playbook requires secrets to be entered. Currently I am handling that by prompting the user using the vars-prompt module and setting it to private so it isn't stored in the bash logs, which means the playbook should be run manually. We could add it as a terraform variable but I'm not sure if you are comfortable having the secrets (slack api token and the email app password) in the statefile on oci. The slack secret is capable only of sending messages to users on the compute cluster workspace, but the password secret is capable of accessing a safe.ai email address and thus would be able to potentially view drive documents if we setup a shared drive in the future. We could create restrictions on this user to prevent this, but that secret should be protected (can be revoked easily if we detect a leak).

If you are comfortable having those secrets on oci then I can implement it to run automatically and move it to the slurm role.

2023-06-14 22:12 UTC, steven-basart requested changes

2023-06-14 22:12 UTC, steven-basart commented on playbooks/README.md
> +4. Press "Generate" in the bottom right and copy this password (This is copied into the terminal window)
Markdown numbering :)

If you ever forget just remember [Smitty Werbenjagermanjensen](https://www.youtube.com/watch?v=RS7mk-UtdjQ)

2023-06-14 22:12 UTC, steven-basart commented on playbooks/goslmailer_install.yml
Okay I'm okay with it as is but maybe a new suggestion is just to make a cais_playbooks folder and oci_playbooks and put them in their respective places.  It's just getting a bit messy I feel with a lot of playbooks.

2023-06-14 22:12 UTC, steven-basart commented on playbooks/roles/slurm/templates/slurm.conf.j2
> +MailProg=/bin/goslmailer
This doesn't appear to get removed when running the [goslmailer_uninstall.yml](https://github.com/centerforaisafety/cerberus-cluster/pull/109/files#diff-1b04a40374a99a2f4c513a9ff06e2269f1ce2ef17abdbb2ad1f7a4ec7e5139c0) Will it cause issues if left in? Maybe update the README and remove that it isn't idempotent if we need to manually do this.

2023-06-14 22:18 UTC, rumiahkessel commented on playbooks/roles/slurm/templates/slurm.conf.j2
> +MailProg=/bin/goslmailer
Tested it on the dev server and it will throw an error in the slurmctld logs but won't cause any problems with running jobs or the like. I can add to the readme though that if you do uninstall you might want to remove this just to be clean.

2023-06-14 23:49 UTC, rumiahkessel commented on playbooks/README.md
> +4. Press "Generate" in the bottom right and copy this password (This is copied into the terminal window)
I am mad at this plugin... Addressed

2023-06-14 23:52 UTC, rumiahkessel commented on playbooks/goslmailer_install.yml
Made a new issue for this: https://github.com/centerforaisafety/cerberus-cluster/issues/113

2023-06-14 23:56 UTC, andriy-safe-ai approved these changes
LGTM

2023-06-15 00:01 UTC, steven-basart approved these changes
Squish them merge :)

2023-06-15 00:06 UTC, merged