Comment out monitoring cron if unused.
centerforaisafety/cerberus-cluster pull request #119
Opened 2023-06-20 17:01 UTC by steven-basart

2023-06-22 21:56 UTC, steven-basart commented
Gotta rebase this branch

2023-06-23 16:41 UTC, andriy-safe-ai requested changes

2023-06-23 16:49 UTC, steven-basart commented on playbooks/roles/cron/tasks/el.yml
> +    minute: "#*"
Good find! I like it.

I switched to using the built in ansible disabled.

2023-06-23 16:50 UTC, steven-basart commented on playbooks/roles/cron/tasks/el.yml
>      job: "#source /opt/oci-hpc/monitoring/env; /opt/oci-hpc/monitoring/monitor_slurm.sh >> /opt/oci-hpc/monitoring/monitor_slurm_`date '+\\%Y\\%m\\%d'`.log 2>&1"
Switched everything to `disabled: true`

2023-06-23 16:50 UTC, steven-basart commented on playbooks/roles/cron/tasks/el.yml
>      job: "#source /opt/oci-hpc/monitoring/env; /opt/oci-hpc/monitoring/monitor_oci.sh >> /opt/oci-hpc/monitoring/monitor_oci_`date '+\\%Y\\%m\\%d'`.log 2>&1"
Twitter needs the hashtags bro!

2023-06-23 16:51 UTC, steven-basart commented
fixed it @andriy-safe-ai

2023-06-23 17:30 UTC, andriy-safe-ai approved these changes
LGTM

2023-06-23 17:44 UTC, merged