Admin notifications
centerforaisafety/cerberus-cluster pull request #128
Opened 2023-06-22 18:27 UTC by rumiahkessel

Issue: https://github.com/centerforaisafety/cerberus-cluster/issues/118

Added admin notifications for a chosen Slack channel to Slurm. Also fixed a problem where ansible was logging the secrets (protected by permissions but it isn't best practice). Which notifications run can be changed using slurm commands specified in the admin docs (I will link pr here when I finish it). Once a healthy balance is found we can edit the playbook to only enable those notifications.

Added the isntall to the original `goslmailer_install.yml` script and changed its name to `notifications_install` to be more accurate (same for uninstalls). I left the role the same as it still installs from the github goslmailer release.

Currently these are all the situations that trigger a notification with a * if we have tested it:
backup_slurmctld_assumed_control *
backup_slurmctld_failure *
backup_slurmctld_resumed_operation *
node_down*
node_drain*
node_fail*(for some reason says drain instead of fail. Seems to be because this is considered a transient state)
node_up*
primary_database_failure
primary_database_resumed_operation *
primary_slurmctld_acct_buffer_full
primary_slurmctld_failure *
primary_slurmctld_resumed_control *
primary_slurmctld_resumed_operation *
primary_slurmdbd_failure
primary_slurmdbd_resumed_operation  *

2023-06-22 19:38 UTC, steven-basart commented
Can we move the majority of the logic out of the main playbook and into the tasks file?

2023-06-22 22:36 UTC, rumiahkessel commented
Addressed. Chose to not breakdown the uninstall script as when I did it made it less readable not more. However, install is now broken down into component pieces and vast majority of the logic is at the role level. Also separated the admin notifications and goslmailer sections of the role for readability.

2023-06-22 23:37 UTC, steven-basart requested changes

2023-06-22 23:37 UTC, steven-basart commented on playbooks/notifications_install.yml
> +  tasks:
Can these be included with the notifications role too?

2023-06-22 23:37 UTC, steven-basart commented on playbooks/notifications_uninstall.yml
> +    command: strigger --clear --user slurm
This clears all striggers no? 
Kinda "dangerous" if we ever add others and then run this script.

2023-06-22 23:37 UTC, steven-basart commented on playbooks/roles/notifications/files/triggers/node_fail.sh
> +MESSAGE=":red_circle: <!channel> $* has Failed"
Can you check how often if ever this has happened? I basically want to avoid any alerts that are "spammy"

2023-06-23 00:00 UTC, rumiahkessel commented on playbooks/notifications_install.yml
> +  tasks:
ideally we would, but they need to be run only on the bastion and you can't change hosts at the role level. I also like having them at the playbook level as it makes it easy to find them if you want to change which triggers are run.

2023-06-23 00:02 UTC, rumiahkessel commented on playbooks/notifications_uninstall.yml
> +    command: strigger --clear --user slurm
There isn't really a better way to do this as far as I can see. You can only search triggers by their id which is generated on install. I can write a script that uses the get function and then parse the output to make this safer. Will be much more involved though

2023-06-23 00:03 UTC, rumiahkessel commented on playbooks/roles/notifications/files/triggers/node_fail.sh
> +MESSAGE=":red_circle: <!channel> $* has Failed"
we weren't able to make it happen consistently on dev as it seems it may be a transient state. Andriy and I thought we should install all the notifications and if any are excessive it is very easy to disable them while still in prod. We messed around with forcing nodes to change states and none of the notifications were very excessive, but I believe this one will only trigger when an actual job causes a node to fail and I am not aware of a way to simulate that.

2023-06-23 00:07 UTC, rumiahkessel commented on playbooks/notifications_uninstall.yml
> +    command: strigger --clear --user slurm
working on this now as I think I can do it a little more easily than I first thought

2023-06-23 05:11 UTC, rumiahkessel commented on playbooks/notifications_uninstall.yml
> +    command: strigger --clear --user slurm
made a commit addressing this. CRLF line endings caused me so much needless pain...

2023-06-23 12:38 UTC, steven-basart commented on playbooks/notifications_uninstall.yml
> +    command: strigger --clear --user slurm
Yup with items works.

2023-06-23 12:39 UTC, steven-basart commented on playbooks/roles/notifications/files/triggers/node_fail.sh
> +MESSAGE=":red_circle: <!channel> $* has Failed"
Sorry I just meant like look in graphana to see if this state has happened a lot recently.

2023-06-23 18:12 UTC, rumiahkessel commented on playbooks/roles/notifications/files/triggers/node_fail.sh
> +MESSAGE=":red_circle: <!channel> $* has Failed"
Oh I see. In the last 90 days it hasn't shown on the fail chart, but it seems that that graph only tracks down and drain. The resources I have found say that fail is nearly identical to drain only slightly more severe where the system expects the node to go unresponsive and so tries to move its jobs to other nodes. We may find that it notifies more than we like but it is a single command to disable it if it is. Entirely up to you whether you want me to keep it in.

2023-06-23 18:14 UTC, steven-basart commented on playbooks/roles/notifications/files/triggers/node_fail.sh
> +MESSAGE=":red_circle: <!channel> $* has Failed"
Sounds good. Leave it.

2023-06-23 18:15 UTC, steven-basart approved these changes
LGTM

READY TO SQUANCH

2023-06-23 18:21 UTC, andriy-safe-ai approved these changes
LGTM

2023-06-23 18:39 UTC, merged