Slurm upgrade
centerforaisafety/cerberus-cluster pull request #129
Opened 2023-06-23 06:30 UTC by steven-basart

2023-06-23 16:10 UTC, andriy-safe-ai requested changes

2023-06-23 16:10 UTC, andriy-safe-ai commented on playbooks/slurm_upgrade.yml
> +  tasks:
Add `become: true` below `hosts: ...`. That way you don't have to repeat yourself in each task.

2023-06-23 16:10 UTC, andriy-safe-ai commented on playbooks/slurm_upgrade.yml
> +  tasks:
Do that for each play.

2023-06-23 16:56 UTC, steven-basart commented on playbooks/slurm_upgrade.yml
> +  tasks:
destroying hopes and dreams of those becomers you know

2023-06-23 16:56 UTC, steven-basart commented on playbooks/slurm_upgrade.yml
> +  tasks:
it has been done though.

2023-06-26 20:09 UTC, andriy-safe-ai requested changes

2023-06-26 20:13 UTC, steven-basart commented on playbooks/slurm_upgrade.yml
> +  gather_facts: true
No this calls Oracle's packages which might mess things up if run as root.

2023-06-26 20:14 UTC, andriy-safe-ai approved these changes
LGTM!

2023-06-26 21:00 UTC, merged