250 billing system
centerforaisafety/cerberus-cluster pull request #252
Opened 2023-12-21 16:35 UTC by andriy-safe-ai

2023-12-21 17:11 UTC, xksteven commented on schema.yaml
> +    description: "Billing Shape Name"
Use sentences or don't use periods on 1572,

2023-12-21 17:18 UTC, andriy-safe-ai commented on mysql.tf
> +    backup_policy {
How often are backups made? Daily? Confirm this.

2023-12-21 17:20 UTC, andriy-safe-ai commented on mysql.tf
> +    freeform_tags = {
Can we add a creation date tag?

2023-12-21 17:21 UTC, andriy-safe-ai commented on mysql.tf
> +    port_x = "33060"
Should we remove this?

2023-12-21 17:29 UTC, andriy-safe-ai commented on playbooks/roles/billing/tasks/main.yml
> +- name: Source billing database environment variables
Update name

2023-12-21 17:34 UTC, xksteven requested changes
Should update the README.  
Also give an example of how to insert a full example for fake user in the database.  Maybe a quick unit test for the database could also work.

2023-12-21 17:34 UTC, xksteven commented on mysql.tf
> +    port_x = "33060"
Que es eso?

2023-12-21 17:34 UTC, xksteven commented on mysql.tf
> +    data_storage_size_in_gb = "50"
How easy or hard is it to expand it?  Is there a way to make this dynamic?

2023-12-21 17:34 UTC, xksteven commented on bastion.tf
> +      billing_mysql_ip = var.billing ? oci_mysql_mysql_db_system.billing_mysql_db_system[0].ip_address : "",
Where is the ip_address defined? Does OCI define it for us?

2023-12-21 17:34 UTC, xksteven commented on mysql.tf
> +    backup_policy {
what is the frequency of these backups?

2023-12-21 17:34 UTC, xksteven commented on playbooks/roles/billing/files/billing.sql
> +    resource_name VARCHAR(255) NOT NULL
add a resource_description TEXT

2023-12-21 17:34 UTC, xksteven commented on playbooks/roles/billing/files/billing.sql
> +CREATE TABLE IF NOT EXISTS billing.resource_specifications (
Can you give an example or a comment of the difference between resource type and resource specification?

2023-12-21 17:34 UTC, xksteven commented on playbooks/roles/billing/files/billing.sql
> +    ('Network');
spacing

2023-12-21 17:41 UTC, xksteven commented on playbooks/roles/billing/files/billing.sql
> +INSERT INTO billing.resource_specifications (resource_type_id, specification_name, unit_id)
instead of unit_id can we call it measurement_unit_id longer but more descriptive.

2023-12-21 17:43 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing.sql
> +INSERT INTO billing.resource_types (resource_name)
Associate units of measure with resource types instead of resource specifications.

2023-12-21 17:48 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_network_egress.sh
> +PASSWORD=''  # Consider moving to a more secure method
Use either a terraform or ansible configuration file to store the password. Get it from there.

2023-12-21 18:00 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing.sql
> +INSERT INTO billing.resource_specifications (resource_type_id, specification_name, unit_id)
Add login-node-egress

2023-12-21 18:01 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing.sql
> +INSERT INTO billing.resource_specifications (resource_type_id, specification_name, unit_id)
Change `network-egress` to `compute-node`network`egress` or something similar.

2023-12-21 18:02 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_network_egress.sh
> +#!/bin/bash
Add error logging.

2023-12-21 18:03 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_network_egress.sh
> +#!/bin/bash
Add alerts for errors. Add a GitHub issue.

2023-12-21 18:06 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_filesystem_usage.sh
> +declare -A PAID_USERS
Remove this.

2023-12-21 18:06 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_filesystem_usage.sh
> +        if [[ ${PAID_USERS[$USER_NAME]+_} ]]; then
Remove this.

2023-12-21 18:07 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_filesystem_usage.sh
> +declare -A PAID_USERS
We are no longer filtering for paid users.

2023-12-21 18:07 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_filesystem_usage.sh
> +        if [[ ${PAID_USERS[$USER_NAME]+_} ]]; then
We are no longer filtering for paid users.

2023-12-21 18:08 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_filesystem_usage.sh
> +# Usage:
Update usage to explicitly state that the script should be run hourly.

2023-12-21 18:10 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_gpu_usage.sh
> +declare -A PAID_USERS
Remove this. We are no longer filtering for rapid users.

2023-12-21 18:10 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_gpu_usage.sh
> +        if [[ ${PAID_USERS[$USER_NAME]+_} ]]; then
Remove this. We are no longer filtering for paid users.

2023-12-21 18:11 UTC, xksteven commented on playbooks/roles/billing/files/billing_gpu_usage.sh
> +            GPU_QUANTITY=$(extract_gpu_quantity $ALLOC_TRES)
Need to track multiple node requests

2023-12-27 19:31 UTC, andriy-safe-ai commented on bastion.tf
> +      billing_mysql_ip = var.billing ? oci_mysql_mysql_db_system.billing_mysql_db_system[0].ip_address : "",
Yes, it is OCI defined.

2023-12-27 19:33 UTC, andriy-safe-ai commented on mysql.tf
> +    data_storage_size_in_gb = "50"
Easy to expand from OCI. We cannot make it dynamic.

2023-12-27 19:35 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_gpu_usage.sh
> +declare -A PAID_USERS
We are still filtering by paid users.

2023-12-27 19:35 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_gpu_usage.sh
> +            GPU_QUANTITY=$(extract_gpu_quantity $ALLOC_TRES)
We confirmed that we can do this during our code review session.

2023-12-27 19:37 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_network_egress.sh
> +#!/bin/bash
https://github.com/centerforaisafety/cerberus-cluster/issues/253

2023-12-27 19:37 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing_network_egress.sh
> +PASSWORD=''  # Consider moving to a more secure method
We're using an ansible configuration files to store the password.

2023-12-27 19:38 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing.sql
> +INSERT INTO billing.resource_specifications (resource_type_id, specification_name, unit_id)
yes

2023-12-27 20:59 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing.sql
> +    resource_name VARCHAR(255) NOT NULL
Ok.

2023-12-27 21:00 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/billing.sql
> +CREATE TABLE IF NOT EXISTS billing.resource_specifications (
Resource type Ex: GPU. Resource specifications Ex: A100, H100.

2024-03-16 00:39 UTC, steven-basart commented
Whatever happened to this PR?

2024-03-19 03:34 UTC, andriy-safe-ai commented
@steven-basart 


I'll need to find some time to resolve the merge conflicts. Either later this week or early next week.

2024-04-04 20:02 UTC, andriy-safe-ai commented on schema.yaml
> +    description: "Billing Shape Name"
Not sure what you are referring to.

2024-04-04 20:03 UTC, andriy-safe-ai commented on mysql.tf
> +    backup_policy {
Daily

2024-04-08 19:41 UTC, steven-basart commented on mysql.tf
> +        is_delete_protected = "true"
Just make sure it's not impossible to delete it.

2024-04-08 20:30 UTC, steven-basart requested changes
Some changes

2024-04-08 20:30 UTC, steven-basart commented on playbooks/roles/billing/files/invoice.sh
> +DB_PASS=""
Is this file readable by users?

2024-04-08 20:30 UTC, steven-basart commented on playbooks/roles/cais-all/tasks/ol-7.yml
> -  when: "'/etc/cron.d/ksplice' is file"
? Seems like you added a bunch of commented code here.

2024-04-08 20:30 UTC, steven-basart commented on playbooks/roles/packages/tasks/ol-7.yml
> +- name: Install SCL for GCC v7
This could just be separate tiny PR.

2024-04-08 20:30 UTC, steven-basart commented on schema.yaml
> +    description: "Billing Shape Name"
I don't remember.  Probably the descriptions to use sentences and not just repeat the variable name.

2024-04-24 14:29 UTC, andriy-safe-ai commented on playbooks/goslmailer_install.yml
> +- name: Download and unpack from github as well as get user prompt
Yes. The goslmailer files got removed accidentally when we rebased main with oci-hpc. I'm re-adding the goslmailer files through the billing branch as I didn't remove them when I rebased this branch. Not related to billing but I don't want to create another branch/PR just to re-add these files.

2024-04-24 14:33 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/invoice.sh
> +DB_PASS=""
It would not be.

2024-04-24 14:40 UTC, andriy-safe-ai commented on playbooks/roles/cais-all/tasks/ol-7.yml
> -  when: "'/etc/cron.d/ksplice' is file"
Removed.

2024-04-24 14:48 UTC, andriy-safe-ai commented on playbooks/README.md
> +If the billing system has been deployed a final step needs to be performed before usage data will be collected. The `bash` scripts in `/etc/oci-hpc/billing` need to be scheduled with a cron job. Inst
Updated with crontab entries.

2024-04-25 19:48 UTC, steven-basart commented on playbooks/roles/billing/files/billing_gpu_usage.sh
> +    local usage_per_user=$(sacct -a -X --partition $PARTITION --format=user,elapsed,AllocTRES --starttime ${DATE}T00:00:00 --endtime ${DATE}T23:59:59 --state=bf,ca,cd,dl,f,nf,oom,pr,to --parsable2)
should we add the --noheader?

2024-06-14 02:56 UTC, andriy-safe-ai commented on mysql.tf
> +        is_delete_protected = "true"
It's not.

2024-06-19 15:26 UTC, xksteven requested changes
Small change

2024-06-19 23:48 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/invoice.sh
> +  query=$(generate_sql_query "$resource_spec_id" "$usage_divisor" "$cost_divisor" "$ACCOUNT_NAME")
Account name is not required. If you don't provide an account name a wild card character is used to generate an invoice for all accounts.

2024-06-19 23:48 UTC, andriy-safe-ai commented on playbooks/roles/billing/files/invoice.sh
> +  query=$(generate_sql_query "$resource_spec_id" "$usage_divisor" "$cost_divisor" "$ACCOUNT_NAME")
@steven-basart

2024-06-21 00:43 UTC, steven-basart approved these changes

2024-06-21 03:30 UTC, andriy-safe-ai commented
Rebased to one commit.

2024-06-21 03:30 UTC, merged