262 nix fix
centerforaisafety/cerberus-cluster pull request #263
Opened 2024-03-06 01:00 UTC by andriy-safe-ai

Rewrote playbooks to install Nix on boot volume of login node. Removed socat. Set Flakes flag to false.

2024-03-06 23:32 UTC, steven-basart requested changes
Can you leave a comment or a name where the /nix directory gets shared to everything as ro?  I think I missed it in initial pass.

2024-03-06 23:32 UTC, steven-basart commented on playbooks/install_nix.yml
>      - shell: |
Can you leave a comment for this line:
"nix_version_on_system: "{{ (nix_version_output.stdout_lines[0].split(' '))[2] }}""

It looks fugly. 
What if nix changes the way it's formatted it's output? Can it pass?

2024-03-06 23:32 UTC, steven-basart commented on playbooks/install_nix.yml
> -- name: Ensure /data/nix/var/nix/ dir exists
Are you manually deleting these dirs?

2024-03-06 23:32 UTC, steven-basart commented on playbooks/install_nix.yml
> +    - name: Install Nix
Recursion? Looks weird

2024-03-06 23:32 UTC, steven-basart commented on playbooks/install_nix.yml
> +- hosts: login
Why don't these have names?

2024-03-06 23:32 UTC, steven-basart commented on playbooks/install_nix.yml
> +- hosts: bastion, slurm_backup, compute
No name?

2024-03-07 00:51 UTC, andriy-safe-ai commented on playbooks/install_nix.yml
> -- name: Ensure /data/nix/var/nix/ dir exists
No, there is a separate uninstall playbook. To uninstall the existing Nix installation I'm going to run the old uninstall playbook. The new uninstall playbook is written to uninstall the new installation.

2024-03-07 01:39 UTC, andriy-safe-ai commented on playbooks/install_nix.yml
>      - shell: |
Good point. There is no guarantee that we will be able to parse the version correctly if the output format changes. 

I've rewritten it to just check if Nix is installed or not. Also removed the crazy parser line. Much cleaner too.

2024-03-07 01:40 UTC, andriy-safe-ai commented on playbooks/install_nix.yml
> +- hosts: login
Added names.

2024-03-07 01:46 UTC, andriy-safe-ai commented on playbooks/install_nix.yml
> +    - name: Install Nix
Removed the name from the task.

2024-03-07 01:46 UTC, andriy-safe-ai commented on playbooks/install_nix.yml
> +- hosts: bastion, slurm_backup, compute
Added name.

2024-03-07 02:34 UTC, steven-basart commented on playbooks/install_nix.yml
> +- name: Check whether is already installed
Whether nix is installed

2024-03-07 02:56 UTC, steven-basart commented on playbooks/uninstall_nix.yml
> +  hosts: all
Confused I thought the files were only created on the login node then get shared to the others. Do they get physically chopped to all machines?

2024-03-07 03:15 UTC, andriy-safe-ai commented on playbooks/uninstall_nix.yml
> +  hosts: all
Only shared but there is a `/nix` dir on all nodes that I need to remove. I included all since it wouldn't hurt to run the other plays.

2024-03-07 14:44 UTC, andriy-safe-ai commented
The latest changes (34baa44d8a27c84f73ccf0479dbd7a91d6863519) have been tested in a dev cluster. 
- Tested installing (pass)
- Testing uninstalling (pass)
- Testing installing while Nix was already installed (pass)

2024-03-07 16:34 UTC, andriy-safe-ai commented
@steven-basart 
The `nfs-client` and `nfs-server` roles were not changed functionally. The only difference is that I added a newline to separate two plays in `nfs-client/tasks/el.yml`.

2024-03-07 17:13 UTC, steven-basart approved these changes
Seems good to me.

2024-03-07 18:20 UTC, andriy-safe-ai commented
Rebased to one commit. Merged.

2024-03-07 18:20 UTC, merged