Added onboarding script
centerforaisafety/cerberus-cluster pull request #267
Opened 2024-03-16 02:21 UTC by andriy-safe-ai

As for testing I've been using this script for the last few months in production.

2024-03-17 04:21 UTC, steven-basart requested changes
A few changes.

2024-03-17 04:21 UTC, steven-basart commented on bin/onboard.sh
> +researcher_name='' # john_smith
This should be something like account name or Linux username. Makes it more readable to know what the name is being used for compared to their full name.

2024-03-17 04:21 UTC, steven-basart commented on bin/onboard.sh
> +    sudo sacctmgr add account --immediate "$lab_name" Parent="$parent_account" Description="Professor $lab_name Lab" Organization=Prof_"$lab_name"
The deception keyword reads weird with the lab name example. Professor John Smith Lab Lab.

2024-03-17 04:21 UTC, steven-basart commented on bin/onboard.sh
> +
Lastly it would be good to add some light error handling. If "cluster" command fails or doesn't exist just exit the program.

2024-03-19 03:46 UTC, andriy-safe-ai commented on bin/onboard.sh
> +    sudo sacctmgr add account --immediate "$lab_name" Parent="$parent_account" Description="Professor $lab_name Lab" Organization=Prof_"$lab_name"
I agree. I've removed Professor entirely and updated the example lab name to not have Lab in the name itself.

2024-03-19 03:46 UTC, andriy-safe-ai commented on bin/onboard.sh
> +researcher_name='' # john_smith
I'll use cluster_username instead.

2024-03-19 05:36 UTC, andriy-safe-ai commented on bin/onboard.sh
> +
Added some basic error handling.

2024-03-19 05:36 UTC, andriy-safe-ai commented on bin/onboard.sh
> +
Tested on dev cluster.

2024-03-19 05:37 UTC, andriy-safe-ai commented on bin/onboard.sh
> +
Script stops if an error occurs such as a missing variable.

2024-03-27 21:24 UTC, steven-basart requested changes

2024-03-27 21:24 UTC, steven-basart commented on bin/onboard.sh
> +
Add a cluster test here before it's used below.  Something simple like `cluster -v`

2024-03-27 21:24 UTC, steven-basart commented on bin/onboard.sh
> +group_id=$(cluster group list | grep -wA1 "$lab_name" | grep gidNumber | awk '{print $2}')
I've had this one return two numbers recently so this needs to be fixed or give the user more info when it happens for more than 1 group_id

2024-03-27 21:32 UTC, andriy-safe-ai commented on bin/onboard.sh
> +group_id=$(cluster group list | grep -wA1 "$lab_name" | grep gidNumber | awk '{print $2}')
I think I've fixed this issue. I used to run into a problem when adding a user to `cais` because we also have `cais_friends` that would get returned. To fix this I've added the `-w` option to the grep command so that we only return exact lab name matches.

2024-03-27 21:50 UTC, andriy-safe-ai commented on bin/onboard.sh
> +
Added.

2024-03-27 22:21 UTC, steven-basart commented on bin/onboard.sh
> +group_id=$(cluster group list | grep -wA1 "$lab_name" | grep gidNumber | awk '{print $2}')
Fix the command in the onboarding too ples.

2024-03-27 22:21 UTC, steven-basart approved these changes
LGTM

2024-03-27 22:23 UTC, merged