10 add ha nfs
centerforaisafety/cerberus-cluster pull request #44
Opened 2023-04-11 17:04 UTC by AndriyNovykov

Create 5 playbooks. The swap playbooks swap the FSS home and data directories with the high availability NFS home and data directories. The ha_nfs playbooks are the updated versions of the site, new_nodes, and resize_add playbooks.

2023-04-11 20:35 UTC, xksteven requested changes
Some changes to be made

2023-04-11 20:35 UTC, xksteven commented on playbooks/ha_nfs_new_nodes.yml
> +
which file calls these? 
Are the missing the starting triple dash?

2023-04-11 20:35 UTC, xksteven commented on playbooks/ha_nfs_new_nodes.yml
> +
extra newline

2023-04-11 20:35 UTC, xksteven commented on playbooks/ha_nfs_new_nodes.yml
> +
Run a linter.

2023-04-11 20:35 UTC, xksteven commented on playbooks/ha_nfs_new_nodes.yml
> +        name: hyperthreading
Why are we doing this?

2023-04-11 20:35 UTC, xksteven commented on playbooks/ha_nfs_site.yml
> +
Missing the three dashes

2023-04-11 20:35 UTC, xksteven commented on playbooks/ha_nfs_resize_add.yml
> +- hosts: compute_to_add
Missing the three dashes.

2023-04-11 20:35 UTC, xksteven commented on playbooks/ha_nfs_resize_add.yml
> +- hosts: compute_to_add
Is `compute_to_add` a valid host?

2023-04-11 20:35 UTC, xksteven commented on playbooks/ha_nfs_site.yml
> +
formatting. Run a linter ples.

2023-04-11 20:35 UTC, xksteven commented on playbooks/swap_data.yml
> +---
These should only be run once right?  Need to put in guards in place for that.  `run_once` in ansible or something.

2023-04-11 20:35 UTC, xksteven commented on playbooks/swap_home.yml
> +---
Same here about adding guards.

2023-04-11 20:36 UTC, xksteven commented
Add a README to the directory to at least explain your additional playbooks.  We can add in more details later.

2023-04-11 20:37 UTC, AndriyNovykov commented on playbooks/ha_nfs_new_nodes.yml
> +
The original file didn't have them so I don't believe them.

2023-04-11 20:44 UTC, AndriyNovykov commented on playbooks/ha_nfs_new_nodes.yml
> +        name: hyperthreading
This was done in the original playbook.

2023-04-11 20:44 UTC, xksteven commented on playbooks/swap_data.yml
> +        state: unmounted
Add when conditonal to check if path exists

2023-04-11 21:44 UTC, AndriyNovykov commented on playbooks/swap_data.yml
> +---
Running multiple times does not cause any issues. Ansible first checks whether the export is mount or not before trying to mount or unmount.

2023-04-11 21:49 UTC, xksteven commented on playbooks/ha_nfs_new_nodes.yml
> +        name: hyperthreading
Let's just make a new git issue to remove them

2023-04-11 21:50 UTC, xksteven commented on playbooks/swap_data.yml
> +---
Have you run it more than once as a test? 
Can you show the output?

In my head I think it'll error out.

2023-04-11 22:25 UTC, AndriyNovykov commented on playbooks/swap_data.yml
> +        state: unmounted
Removed src and fstype. They are no longer needed for the Ansible mount module. 
https://github.com/ansible/ansible-modules-core/pull/1357 for reference.

2023-04-11 22:37 UTC, xksteven requested changes
Few more changes.

2023-04-11 22:37 UTC, xksteven commented on playbooks/ha_nfs_site.yml
> +
How did this get past the linter?

2023-04-11 22:38 UTC, xksteven requested changes
Update readme

2023-04-11 22:38 UTC, xksteven commented on playbooks/README.md
> +Then remove the 'ha_nfs_' prefix from the playbooks that have the 'ha_nfs_'.
This is very unclear especially as a README. 

These steps should just already be in a playbook too. 

Stuff I'd expect to see instead (Can include one or more of the following):

- General descriptive of the playbooks/folder
- How to run a playbook
- What happens when you run one (any) of them?
- When should you run one of them?
- Repeat the above two for each playbook.
- Credits feel free to say you wrote some of it.
- maybe give the README a cool title

2023-04-11 22:40 UTC, xksteven commented on playbooks/swap_data.yml
> +        state: unmounted
Double check which ansible version were using too to confirm it's okay to remove.

2023-04-13 21:09 UTC, xksteven commented
Now that we know it'll come in handy let's add the revert of mounting NFS with FSS

2023-04-17 23:05 UTC, steven-basart commented on playbooks/README.md
> +Those playbooks that can be run manually are:
Example 
- add_root_ssh_key.yml
    - This is run to Add an ssh key to /root to be able to unmount the /home directories. Should only be run once when creating the NFS.  
    
As an aside
When is they key removed?

2023-06-14 01:58 UTC, steven-basart commented
I think we can close this now? @andriy-safe-ai

2023-06-15 15:01 UTC, steven-basart commented
I think we can safely close this PR at this point. We can maybe revisit the NFS later but several other work needs to be done first. 

Getting example workloads, RCA, and researching the right solution for next time.

2023-06-15 15:01 UTC, closed without merging