55 add nix package manager
centerforaisafety/cerberus-cluster pull request #89
Opened 2023-05-19 16:18 UTC by andriy-safe-ai

2023-05-19 18:37 UTC, steven-basart requested changes
did a quick review.  Left a few comments.  

Also if you could please post your tests.

2023-05-19 18:37 UTC, steven-basart commented on playbooks/README.md
replace "files" with file names to be more descriptive.

2023-05-19 18:37 UTC, steven-basart commented on playbooks/files/socat-client.service
move the files directory into playbooks/roles/nix/files/ or playbooks/roles/nix/templates/

see [slurm folder](https://github.com/centerforaisafety/cerberus-cluster/tree/main/playbooks/roles/slurm) as an example

2023-05-19 18:37 UTC, steven-basart commented on playbooks/roles/cais-all/tasks/ol-7.yml
why is this line or file even edited?

2023-05-19 18:37 UTC, steven-basart commented on playbooks/roles/nix/tasks/main.yml
> +      ansible.builtin.shell:
you can shorten this to just `shell`

2023-05-20 01:33 UTC, andriy-safe-ai commented on playbooks/files/socat-client.service
Even if the files aren't used in the role?

Make sense from since they're only used for Nix tho.

2023-05-20 01:35 UTC, andriy-safe-ai commented on playbooks/roles/cais-all/tasks/ol-7.yml
An idea that didn't work out. I'll remove any changes.

2023-05-20 01:35 UTC, andriy-safe-ai commented on playbooks/roles/nix/tasks/main.yml
> +      ansible.builtin.shell:
👍

2023-05-20 01:35 UTC, andriy-safe-ai commented on playbooks/README.md
sg

2023-05-20 01:52 UTC, steven-basart commented on playbooks/files/socat-client.service
It's about keeping things organized. Having a general files folder doesn't help anyone when they need to search for the nix configurations and other related info.

2023-05-22 22:35 UTC, steven-basart commented on playbooks/roles/nix/files/socat-client.service
You should be able to get the IP of the slurm backup node via Ansible. Add that as another issue. 

Change the IP to be ###.###.###.## so the files in nix role fails instead of trying to change a random IP.

2023-05-24 16:24 UTC, merged